Newsweek: request project approval
Gnwin/Godwin-Ana-Hubner-Newsweek-project pull request #1
Opened 2020-11-07 06:52 UTC by Gnwin

## Newsweek Clone completion.

In this project, we created the Newsweek website at www.newsweek.com using:
The Bootstrap framework,
HTML,
and CSS.

2020-11-07 08:02 UTC, PhillipUg requested changes
Hey **Ana Dessoy Hübner & Godwin Nwachukwu**, 👋

You have done a great job on this project!  

However, you need to work on a couple of project requirements before you can move on to the next project

### Changes Required ♻️ 

- [x] You have some linter errors. Please make sure you don't have any linter errors before you submit for review

- [x] The hamburger icon that appears at the extreme end on the right should not be present on the large screen size unless you scroll down or if you're on the tablet and mobile screen sizes.

- [ ] The sports section, towards the bottom has only one item on the right, unlike the others which have three. Please check it out

- [ ] On mobile screen size, padding appears towards the right. please fix this

Original Page | Your page
------------ | -------------
![www newsweek com_](https://user-images.githubusercontent.com/20542425/98435764-b3709980-20e6-11eb-8909-d4379a7fdd95.png)  | ![gnwin github io_Godwin-Ana-Hubner-Newsweek-project_](https://user-images.githubusercontent.com/20542425/98435766-bcfa0180-20e6-11eb-8b80-0ebf8a7c3c2e.png)

### Optional Changes:

If you want to make your project even better 🔥💥, I left a few suggestions you can implement. 
These are completely [Optional]: 🦔

- [ ] On mobile and tablet screen sizes, your navbar hides halfway every time I scroll down

- [ ] You excluded the tags on some images like `Tech & Science` and `News`. see image below
![screenshot-www newsweek com-2020 11 07-10_53_24](https://user-images.githubusercontent.com/20542425/98435873-abfdc000-20e7-11eb-8348-68875fe82b32.png)

- [ ] On large screen, your navbar is not fixed. it disappears when you scroll down

#### Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack as **Phillip Musiime**
I would be happy to help! 👩‍💻 


Happy coding 🤓

2020-11-07 08:02 UTC, PhillipUg commented on assets/stylesheets/style.css
> +	z-index: 2; */
- [x] Remove all commented pieces of code

2020-11-08 16:25 UTC, Gnwin commented
## Newsweek Clone Completion

All required changes have been applied

2020-11-08 16:37 UTC, PhillipUg approved these changes
# Status: Project Approved! 🥇 

Congratulations on making all the requested changes and getting this project approved. :+1:

- [OPTIONAL]: Consider adding screenshots to your README to make it look more professional

You can merge this branch into the master branch when you're ready and go on to your next project.
:bulb:  Do not forget to submit your project completion form after merging this branch.

All the best team,

For any assistance, you can contact me on slack as: **Phillip Musiime**

2020-11-08 16:59 UTC, merged